- name: Kubernetes prerequisites setup
  hosts: all
  become: true
  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Remove swap entry from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*swap)'
        replace: '# \1'

    - name: Ensure modules-load.d exists
      file:
        path: /etc/modules-load.d
        state: directory
        mode: '0755'

    - name: Load kernel modules
      copy:
        dest: /etc/modules-load.d/k8s
        content: |
          overlay
          br_netfilter

    - name: Ensure kernel modules are loaded
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Configure sysctl params for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl params
      command: sysctl --system

    - name: Ensure required packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create apt keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download the public signing key for Kubernetes
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: '0644'

    - name: Add Kubernetes apt repository
      deb822_repository:
        name: Kubernetes
        types: deb
        uris: 
          - https://pkgs.k8s.io/core:/stable:/v1.33/deb/
        suites:
          - /
        signed_by: /etc/apt/keyrings/kubernetes-apt-keyring.asc

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - containerd
        state: present

    - name: Hold Kubernetes packages at current version
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable and start containerd service
      systemd:
        name: containerd
        enabled: yes
        state: started

    - name: Ensure /etc/containerd directory exists
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config.toml if missing
      shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Set SystemdCgroup to true in containerd config
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup\s*='
        line: '\1SystemdCgroup = true'
        backrefs: yes
      notify: Restart containerd

  handlers:
    - name: Restart containerd
      service:
        name: containerd
        state: restarted